// ProductData.js
// Import images
import kurti1 from "./Productimage/silkkurti.jpeg";
import kurti2 from "./Productimage/kurtismall.jpeg";
import kurti3 from "./Productimage/kurti3.jpeg";
import suite from './Productimage/mithlasuite1.jpeg';
import suite1 from './Productimage/Mithlasuite.jpeg';
import shorai from './Productimage/shorai.jpeg';
import shorai1 from './Productimage/shorai1.jpeg';
import madhubani from "./Productimage/madhubani.jpeg";
import madhubani1 from "./Productimage/madhubani1.jpeg";
import mathliblue from './Productimage/mathliblue.jpeg';
import mathliblue1 from './Productimage/mathliblue1.jpeg';
import mithilapaint from './Productimage/mithlapaint.jpeg';
import mithilapaint1 from './Productimage/mithlapaint1.jpeg';
import wall from './Productimage/madhubaniwall.jpeg';
import wall1 from './Productimage/madubaniwallhangi1.jpeg';
import wall2 from './Productimage/madhubaniwalhanging2.jpeg';
import kurta from './Productimage/menskurta.jpeg';
import kurta1 from './Productimage/menkurta1.jpeg';
import kidscraft from './Productimage/kidscraft.jpeg';
import kidscraft1 from './Productimage/kidscraft1.jpeg';
import kurtawhite from './Productimage/menkurta2.jpeg';
import kurtawhite1 from './Productimage/menkurta3.jpeg';
import kurtacream from './Productimage/menkurta4.jpeg';
import kurtacream1 from './Productimage/menkurta5.jpeg';
import dupata from './Productimage/dupata1.jpeg';
import dupata1 from './Productimage/dupata.jpeg';
import menkurtas from './Productimage/menkurta7.jpeg';
import menkurta1 from './Productimage/menkurta6.jpeg';
import mithlarthang from './Productimage/mitharthang.jpeg';
import mithlarthang1 from './Productimage/mithlaart.jpeg';
import loutsart from './Productimage/loutsart1.jpeg';
import loutsart1 from './Productimage/loutsart.jpeg';
import radhapaint from './Productimage/radapaint.jpeg';
import radhapaint1 from './Productimage/radhapaint1.jpeg';
import madubanifish from './Productimage/madubanifish1.jpeg';
import madhubanifish1 from './Productimage/madhubanifish.jpeg';
import cover from  './Productimage/cover.jpeg';
import cover1 from  './Productimage/cover1.jpeg';
import madhubani3 from './Productimage/madhubani3.jpeg';
import madhubani4 from './Productimage/madhubani4.jpeg';
import madhubani5 from './Productimage/madhubani5.jpeg';
import madhubani6 from './Productimage/madhubani6.jpeg';
import madhubani7 from './Productimage/madhubani7.jpeg';
import madhubani8 from './Productimage/madhubani8.jpeg';
import budh from './Productimage/budhpainting.jpeg';
import budh1 from './Productimage/budhpainting1.jpeg';
import madhubani9 from './Productimage/madhubani9.jpeg';
import madhubani10 from './Productimage/madhubani10.jpeg';
import madhubani11 from './Productimage/madhubani11.jpeg';
import madhubani12 from './Productimage/madhubani11.jpeg';
import shorahi from './Productimage/shorahitraditional.jpeg';
import shorahi1 from './Productimage/shorahitraditional1.jpeg';
import kohabr from './Productimage/kohabr1.jpeg';
import kohabr1 from './Productimage/kohabr.jpeg';
import madhubani13 from './Productimage/madhubani13.jpeg';
import madhubani14 from './Productimage/madhubani14.jpeg';
import mithla2 from './Productimage/mithla2.jpeg';
import mithla3 from './Productimage/mithla3.jpeg';

// Products Array
export const products = [
  {
    id: 2,
    brand: "Girls Kurti",
    artist: "Ved Prabha",
    currentPrice: "Rs. 1,999",
    originalPrice: "Rs. 2,499",
    discount: "20%",
    images: [kurti1, kurti2, kurti3],
    category: "Textile",
    subcategory: "Girls Kurti",
    rating: 4.3,
    reviews: 127,
    size: ["M", "L", "XL"],
    color: ["White-Cream"],
    material: "Silk",
    description: "Elegant hand-painted Maithili silk kurti, perfect for festive wear.",
  },
  {
    id: 3,
    brand: "Khadi Cotton Mithila Suit Set",
    artist: "Ved Prabha",
    currentPrice: "₹3,500",
    originalPrice: "₹4,200",
    discount: "15%",
    images: [suite, suite1],
    category: "Textile",
    subcategory: "Girls Kurti",
    rating: 4.7,
    reviews: 86,
    size: ["M", "L", "XL"],
    color: ["Cream", "Natural"],
    description: "Khadi cotton suit with Mithila hand painting, breathable & stylish.",
  },
  {
    id: 4,
    brand: "Handmade Sohrai Tribal Painting",
    artist: "Local Tribal Artist",
    currentPrice: "₹499",
    originalPrice: "₹699",
    discount: "28%",
    images: [shorai, shorai1],
    category: "Painting",
    subcategory: "Sohrai Jharkhand Painting",
    rating: 4.5,
    reviews: 42,
    size: ["A4"],
    color: ["Multicolor"],
    description: "Handmade Sohrai tribal painting with vibrant cultural motifs.",
  },
  {
    id: 5,
    brand: "Mithila (Madhubani) Painting",
    artist: "Douli Kumari",
    currentPrice: "₹799",
    originalPrice: "₹999",
    discount: "20%",
    images: [madhubani, madhubani1],
    category: "Painting",
    subcategory: "Mithila Painting",
    rating: 4.6,
    reviews: 58,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Vibrant handmade Mithila painting, perfect for décor & gifting.",
  },
  {
    id: 6,
    brand: "Maithili Painting – Handcrafted Folk Art",
    artist: "Dauli Kumari",
    currentPrice: "₹799",
    originalPrice: "₹999",
    discount: "20%",
    images: [mathliblue, mathliblue1],
    category: "Painting",
    subcategory: "Mithila Painting",
    rating: 4.5,
    reviews: 36,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Authentic Maithili folk painting with intricate hand-painted patterns.",
  },
  {
    id: 7,
    brand: "Authentic Handcrafted Maithili Painting",
    artist: "Vidya Jha",
    currentPrice: "₹1299",
    originalPrice: "₹1599",
    discount: "19%",
    images: [mithilapaint, mithilapaint1],
    category: "Painting",
    subcategory: "Mithila Painting",
    rating: 4.7,
    reviews: 24,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Beautiful Maithili folk art painting with vibrant hand-painted details.",
  },
  {
    id: 8,
    brand: "Hand-Painted Madhubani Wall Hanging",
    artist: "Vidhi Jha",
    currentPrice: "₹999",
    originalPrice: "₹1299",
    discount: "23%",
    images: [wall, wall1, wall2],
    category: "Painting",
    subcategory: "Madhubani Wall Hanging",
    rating: 4.6,
    reviews: 18,
    size: ["A4"],
    color: ["Multicolor"],
    description: "Hand-painted Madhubani wall hanging, perfect for home décor.",
  },
  {
    id: 9,
    brand: "Hand-Painted Mithila Cotton Kurta with Silk Dupatta",
    artist: "Ved Prabha",
    currentPrice: "₹2298",
    originalPrice: "₹2598",
    discount: "12%",
    images: [kurta, kurta1],
    category: "Handcraft & Textile",
    subcategory: "Kurta",
    rating: 4.7,
    reviews: 22,
    size: ["S", "M", "L", "XL"],
    color: ["Multicolor"],
    description: "Mithila cotton kurta with silk dupatta, hand-painted and traditional.",
  },
  {
    id: 10,
    brand: "Hand Work Cotton Kurti Suit Set with Pajama & Dupatta",
    artist: "Ved Prabha",
    currentPrice: "₹2499",
    originalPrice: "₹2999",
    discount: "17%",
    images: [kidscraft1, kidscraft],
    category: "Textile",
    subcategory: "Kids Cloth",
    rating: 4.8,
    reviews: 18,
    size: ["5 Year", "8 Year", "10 Year", "S"],
    color: ["Multicolor"],
    description: "Kids kurti suit set with pajama & dupatta, hand-painted and festive ready.",
  },
  {
    id: 11,
    brand: "Men Mithila Painting Hand Work Cotton Kurta",
    artist: "Ved Prabha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [kurtawhite, kurtawhite1],
    category: "Handcraft & Textile",
    subcategory: "Kurta",
    rating: 4.6,
    reviews: 22,
    size: ["S", "M", "L", "XL", "XXL"],
    color: ["White"],
    description: "Men’s cotton kurta with Mithila hand-painted artwork.",
  },
  {
    id: 12,
    brand: "Men Mithila Painting Hand Work Cotton Kurta",
    artist: "Ved Prabha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [kurtacream, kurtacream1],
    category: "Handcraft & Textile",
    subcategory: "Kurta",
    rating: 4.6,
    reviews: 22,
    size: ["S", "M", "L", "XL", "XXL"],
    color: ["White-cream"],
    description: "Men’s cotton kurta in white-cream, hand-painted Mithila design.",
  },
  {
    id: 13,
    brand: "Mithila Hand-Painted Silk Dupatta",
    artist: "Ved Prabha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [dupata, dupata1],
    category: "Handcraft & Textile",
    subcategory: "Dupatta",
    rating: 4.6,
    reviews: 24,
    size: ["Free Size"],
    color: ["Multicolor"],
    description: "Silk dupatta with hand-painted Mithila artwork, elegant & festive.",
  },
  {
    id: 14,
    brand: "Mithila Hand-Painted Cotton Kurta",
    artist: "Ved Prabha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [menkurtas, menkurta1],
    category: "Handcraft & Textile",
    subcategory: "Kurta",
    rating: 4.5,
    reviews: 32,
    size: ["S", "M", "L", "XL"],
    color: ["Multicolor"],
    description: "Cotton kurta with hand-painted Mithila designs, breathable & festive.",
  },
  {
    id: 15,
    brand: "Madhubani Hand-Painted Wall Art – Peacock Fish Motif",
    artist: "Vidhi Jha",
    currentPrice: "₹799",
    originalPrice: "₹999",
    discount: "20%",
    images: [mithlarthang, mithlarthang1],
    category: "Painting",
    subcategory: "Madhubani Wall Art",
    rating: 4.6,
    reviews: 28,
    size: ["A4"],
    color: ["Multicolor"],
    description: "Peacock fish Madhubani wall art, vibrant and handcrafted.",
  },
  {
    id: 16,
    brand: "Hand-Painted Madhubani Lotus Art",
    artist: "Vidhi Jha",
    currentPrice: "₹999",
    originalPrice: "₹1,199",
    discount: "17%",
    images: [loutsart, loutsart1],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.7,
    reviews: 18,
    size: ["1/4"],
    color: ["Multicolor"],
    description: "Madhubani lotus painting, vibrant, hand-painted & symbolic.",
  },
  {
    id: 18,
    brand: "Handmade Maithili Painting – Radha Krishna Theme",
    artist: "Ved Prabha",
    currentPrice: "₹4,000",
    originalPrice: "₹4,800",
    discount: "17%",
    images: [radhapaint, radhapaint1],
    category: "Painting",
    subcategory: "Mithila Painting",
    rating: 4.9,
    reviews: 12,
    size: ["31 x 21 inches"],
    color: ["Multicolor"],
    description: "Radha Krishna themed Maithili painting, fully handmade & vibrant.",
  },
  {
    id: 19,
    brand: "Handmade Madhubani Fish Painting",
    artist: "Vidya Jha",
    currentPrice: "₹599",
    originalPrice: "₹799",
    discount: "25%",
    images: [madubanifish, madhubanifish1],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.6,
    reviews: 22,
    size: ["1/4"],
    color: ["Multicolor"],
    description: "Madhubani four-fish painting, hand-painted and symbolic.",
  },
  {
    id: 20,
    brand: "Hand-Painted Maithili Art Mobile Cover",
    artist: "Bhavna Jha",
    currentPrice: "₹299",
    originalPrice: "₹399",
    discount: "25%",
    images: [cover, cover1],
    category: "Handcraft & Textile",
    subcategory: "Mobile Cover",
    rating: 4.4,
    reviews: 18,
    size: ["Standard"],
    color: ["Multicolor"],
    description: "Hand-painted Maithili mobile cover, unique and stylish.",
  },
  {
    id: 21,
    brand: "Authentic Madhubani Painting (A2 Size) – Framed Wall Art",
    artist: "Sujata Jha",
    currentPrice: "₹1299",
    originalPrice: "₹1599",
    discount: "20%",
    images: [madhubani3, madhubani4],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.7,
    reviews: 31,
    size: ["A2"],
    color: ["Multicolor"],
    description: "A2 framed Madhubani painting, handcrafted with traditional motifs.",
  },
  {
    id: 22,
    brand: "Madhubani Surya Painting (A3 Size) – Traditional Framed Wall Art",
    artist: "Sujata Jha",
    currentPrice: "₹1199",
    originalPrice: "₹1399",
    discount: "15%",
    images: [madhubani5, madhubani6],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.6,
    reviews: 24,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Madhubani Surya painting, hand-painted and framed, vibrant & traditional.",
  },
  {
    id: 23,
    brand: "Handmade A2 Maithili Madhubani Painting (Traditional Art)",
    artist: "Sujata Jha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [madhubani7, madhubani8],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.7,
    reviews: 31,
    size: ["A2"],
    color: ["Multicolor"],
    description: "A2 handmade Maithili Madhubani painting with vibrant cultural details.",
  },
  {
    id: 24,
    brand: "Handmade Madhubani Buddha Wall Painting with Frame",
    artist: "Sujata Jha",
    currentPrice: "₹1499",
    originalPrice: "₹1799",
    discount: "17%",
    images: [budh, budh1],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.8,
    reviews: 19,
    size: ["A2"],
    color: ["Multicolor"],
    description: "Handmade Buddha Madhubani painting, peaceful & decorative.",
  },
  {
    id: 25,
    brand: "Handmade Madhubani Radha Krishna Wall Hanging Painting",
    artist: "Sujata Jha",
    currentPrice: "₹1199",
    originalPrice: "₹1499",
    discount: "20%",
    images: [madhubani9, madhubani10],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.7,
    reviews: 14,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Radha Krishna Madhubani wall hanging, handmade & cultural.",
  },
  {
    id: 26,
    brand: "Handmade Madhubani Traditional Wall Hanging Painting",
    artist: "Sujata Jha",
    currentPrice: "₹899",
    originalPrice: "₹1199",
    discount: "25%",
    images: [madhubani11, madhubani12],
    category: "Painting",
    subcategory: "Madhubani Painting",
    rating: 4.6,
    reviews: 10,
    size: ["A3"],
    color: ["Multicolor"],
    description: "Traditional Madhubani wall hanging, handcrafted & decorative.",
  },
  {
    id: 27,
    brand: "Sohari Traditional Folk Painting",
    artist: "Local Tribal Artist",
    currentPrice: "₹1299",
    originalPrice: "₹1599",
    discount: "19%",
    images: [shorahi, shorahi1],
    category: "Painting",
    subcategory: "Tribal Folk Art",
    rating: 4.5,
    reviews: 8,
    size: ["A2"],
    color: ["Multicolor"],
    description: "Sohari tribal painting, vibrant and handcrafted with cultural motifs.",
  },
  {
    id: 28,
    brand: "Kohar Handmade Painting",
    artist: "Bhavna Jha",
    currentPrice: "₹1799",
    originalPrice: "₹2199",
    discount: "18%",
    images: [kohabr, kohabr1],
    category: "Painting",
    subcategory: "Kohar / Madhubani Folk Art",
    rating: 4.7,
    reviews: 12,
    size: ["21 x 15 Inch"],
    color: ["Multicolor"],
    description: "Handmade Kohar painting with intricate traditional Madhubani motifs.",
  },
  {
    id: 29,
    brand: "Madhubani Handmade Painting",
    artist: "Ved Prabha",
    currentPrice: "₹1999",
    originalPrice: "₹2499",
    discount: "20%",
    images: [madhubani13, madhubani14],
    category: "Painting",
    subcategory: "Madhubani / Mithila Folk Art",
    rating: 4.8,
    reviews: 9,
    size: ["21 x 15 Inch (Half Size)"],
    color: ["Multicolor"],
    description: "Handmade Madhubani painting by Ved Prabha, vibrant and traditional.",
  },
  {
    id: 30,
    brand: "Maithili Handmade Painting",
    artist: "Ved Prabha",
    currentPrice: "₹1999",
    originalPrice: "₹2499",
    discount: "20%",
    images: [mithla2, mithla3],
    category: "Painting",
    subcategory: "Madhubani / Maithili Folk Art",
    rating: 4.7,
    reviews: 11,
    size: ["21 x 15 Inch (Half Size)"],
    color: ["Multicolor"],
    description: "Beautiful handmade Maithili painting, traditional & vibrant artwork.",
  },
];



